package:
    name: zkdtree
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - pkg-config
        - meson
        - ninja
        - cython
        - numpy
    host:
        - lapack
        - python
        - numpy
    run:
        - python
        - numpy
        - lapack

test:
    requires:
        - {{ compiler("cxx") }}
        - pkg-config
        - meson
        - ninja
        - cython

    source_files:
        - "*"

about:
    author: Zahari Kassabov
    licence: MIT
